/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Institutions */
        get: operations["institutions_api_institutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feed
         * @description The recommended feed, keyset-paginated on (sort key, id desc). ``stage_counts`` counts
         *     the same filter per stage, ignoring the stage filter itself, for the stage chips.
         */
        get: operations["feed_api_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_opportunities__opportunity_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Brief */
        post: operations["create_brief_api_opportunities__opportunity_id__briefs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/rule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_api_alerts_rule_get"];
        /** Put Rule */
        put: operations["put_rule_api_alerts_rule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Channels */
        get: operations["channels_api_alerts_channels_get"];
        put?: never;
        /** Add Channel */
        post: operations["add_channel_api_alerts_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Channel */
        delete: operations["delete_channel_api_alerts_channels__channel_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/channels/{channel_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Channel */
        post: operations["test_channel_api_alerts_channels__channel_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_alerts_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Billing */
        get: operations["billing_api_billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Card */
        post: operations["card_api_billing_card_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_billing_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Credits */
        post: operations["credits_api_billing_credits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_admin_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/{key}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Source */
        post: operations["run_source_api_admin_sources__key__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_admin_sources__key__patch"];
        trace?: never;
    };
    "/api/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_admin_jobs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Queue */
        get: operations["review_queue_api_admin_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/review/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Review */
        post: operations["decide_review_api_admin_review__item_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llm Usage */
        get: operations["llm_usage_api_admin_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evals */
        get: operations["evals_api_admin_evals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document */
        get: operations["document_api_admin_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Relations */
        get: operations["admin_relations_api_admin_relations_get"];
        put?: never;
        /** Review Relation */
        post: operations["review_relation_api_admin_relations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/relations/mixed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mixed Relations */
        get: operations["mixed_relations_api_admin_relations_mixed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/relations/{relation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Relation */
        get: operations["admin_relation_api_admin_relations__relation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opportunity Relations */
        get: operations["opportunity_relations_api_opportunities__opportunity_id__relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/toss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toss Webhook
         * @description Toss retries until it gets a 200, so always answer 200 and reconcile against the API.
         */
        post: operations["toss_webhook_api_webhooks_toss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertChannelIn */
        AlertChannelIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "email" | "slack" | "kakao";
            /** Target */
            target: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** AlertChannelOut */
        AlertChannelOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Target */
            target: string;
            /** Label */
            label: string;
            /** Enabled */
            enabled: boolean;
            /** Last Error */
            last_error: string | null;
        };
        /** AlertRuleIO */
        AlertRuleIO: {
            /**
             * Mode
             * @default daily
             * @enum {string}
             */
            mode: "instant" | "daily" | "weekly";
            /**
             * Min Score
             * @default 0.55
             */
            min_score: number;
            /** Stages */
            stages?: string[];
            /**
             * Quiet Start
             * @default 22
             */
            quiet_start: number;
            /**
             * Quiet End
             * @default 8
             */
            quiet_end: number;
        };
        /** BillingOut */
        BillingOut: {
            subscription: components["schemas"]["SubscriptionOut"];
            /** Credit Balance */
            credit_balance: number;
            /** Brief Cost */
            brief_cost: number;
            /** Plans */
            plans: components["schemas"]["PlanOut"][];
            /** Credit Packs */
            credit_packs: components["schemas"]["CreditPackOut"][];
            /** Ledger */
            ledger: components["schemas"]["LedgerOut"][];
            /** Payments */
            payments: components["schemas"]["PaymentOut"][];
            /** Payment Provider */
            payment_provider: string;
            /** Toss Client Key */
            toss_client_key: string | null;
            /** Customer Key */
            customer_key: string;
        };
        /** BriefOut */
        BriefOut: {
            /** Id */
            id: number;
            /** Content Md */
            content_md: string;
            /** Model */
            model: string;
            /** Credits Spent */
            credits_spent: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BudgetPoint */
        BudgetPoint: {
            /**
             * Observed At
             * Format: date
             */
            observed_at: string;
            /** Amount */
            amount: number;
            /** Stage */
            stage: string;
            /** Stage Label */
            stage_label: string;
        };
        /** CardIn */
        CardIn: {
            /** Auth Key */
            auth_key: string;
            /** Customer Key */
            customer_key: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "smart_city" | "safety_cctv" | "public_sw" | "ai_data" | "mobility" | "energy_env" | "welfare_care" | "education" | "tourism_culture" | "facility" | "other";
        /** CategoryOut */
        CategoryOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** CreditPackOut */
        CreditPackOut: {
            /** Key */
            key: string;
            /** Credits */
            credits: number;
            /** Price Krw */
            price_krw: number;
        };
        /** CreditPurchaseIn */
        CreditPurchaseIn: {
            /** Pack */
            pack: string;
        };
        /** DocumentDetailOut */
        DocumentDetailOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Doc Type */
            doc_type: string;
            /** Parse Method */
            parse_method: string | null;
            /** Text Quality */
            text_quality: number | null;
            /** Text */
            text: string | null;
            /** Chunks */
            chunks: {
                [key: string]: unknown;
            }[];
            /** Structured */
            structured: {
                [key: string]: unknown;
            };
        };
        /** DocumentRef */
        DocumentRef: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Doc Type */
            doc_type: string;
            /** Url */
            url: string | null;
            /** Publisher Raw */
            publisher_raw: string | null;
            /** Parse Method */
            parse_method: string | null;
            /**
             * Published At
             * Format: date
             */
            published_at: string;
        };
        /** EvalRunOut */
        EvalRunOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Git Sha */
            git_sha: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Quote */
            quote: string;
            /** Found */
            found: boolean;
            /** Score */
            score: number;
            /** Start */
            start: number | null;
            /** End */
            end: number | null;
            /** Method */
            method: string;
        };
        /** FeedPage */
        FeedPage: {
            /** Items */
            items: components["schemas"]["OpportunityCard"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
            /**
             * Stage Counts
             * @default {}
             */
            stage_counts: {
                [key: string]: number;
            };
        };
        /** FeedbackIn */
        FeedbackIn: {
            /** Feedback */
            feedback: ("relevant" | "irrelevant" | "won" | "dismissed") | null;
        };
        /** FunnelOut */
        FunnelOut: {
            /** Documents */
            documents: {
                [key: string]: number;
            };
            /** Chunks */
            chunks: number;
            /** Chunks Triaged */
            chunks_triaged: number;
            /** Signals */
            signals: {
                [key: string]: number;
            };
            /** Opportunities */
            opportunities: {
                [key: string]: number;
            };
            /** Review Open */
            review_open: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstitutionOut */
        InstitutionOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Sido */
            sido: string;
            /** Sigungu */
            sigungu: string | null;
            /** Region Code */
            region_code: string;
        };
        /** InstitutionRef */
        InstitutionRef: {
            /** Code */
            code: string | null;
            /** Name */
            name: string;
        };
        /** JobRunOut */
        JobRunOut: {
            /** Id */
            id: number;
            /** Job */
            job: string;
            /** Job Id */
            job_id: string;
            /** Attempt */
            attempt: number;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** LLMUsageOut */
        LLMUsageOut: {
            /** Rows */
            rows: components["schemas"]["LLMUsageRow"][];
            /** Spent Today Usd */
            spent_today_usd: number;
            /** Daily Budget Usd */
            daily_budget_usd: number;
            /** Cache Hit Rate */
            cache_hit_rate: number | null;
            /** Degraded Rate */
            degraded_rate: number | null;
            /** Extractor Mode */
            extractor_mode: string;
        };
        /** LLMUsageRow */
        LLMUsageRow: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Task */
            task: string;
            /** Model */
            model: string;
            /** Status */
            status: string;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** LedgerOut */
        LedgerOut: {
            /** Id */
            id: number;
            /** Delta */
            delta: number;
            /** Balance After */
            balance_after: number;
            /** Reason */
            reason: string;
            /** Ref Type */
            ref_type: string | null;
            /** Ref Id */
            ref_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LinkOut */
        LinkOut: {
            /** Score */
            score: number;
            /** Method */
            method: string;
            /** Tentative */
            tentative: boolean;
            /** Reasons */
            reasons: {
                [key: string]: unknown;
            };
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            org: components["schemas"]["OrgOut"];
            /** Extractor Mode */
            extractor_mode: string;
        };
        /** MixedRelationGroupOut */
        MixedRelationGroupOut: {
            opportunity: components["schemas"]["RelationEndpointOut"];
            /** Project Signal Ids */
            project_signal_ids: number[];
            /** Contract Signal Ids */
            contract_signal_ids: number[];
            /** Bid Notice Numbers */
            bid_notice_numbers: string[];
            /** Reason */
            reason: string;
        };
        /** MixedRelationPageOut */
        MixedRelationPageOut: {
            /** Items */
            items: components["schemas"]["MixedRelationGroupOut"][];
            /** Next After Id */
            next_after_id: number | null;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Channel Id */
            channel_id: number;
            /** Headline */
            headline: string;
        };
        /** OpportunityCard */
        OpportunityCard: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            institution: components["schemas"]["InstitutionRef"];
            /** Department */
            department: string | null;
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Stage */
            stage: string;
            /** Stage Label */
            stage_label: string;
            /** Status */
            status: string;
            /** Est Budget Krw */
            est_budget_krw: number | null;
            /** Bid Window Start */
            bid_window_start: string | null;
            /** Bid Window End */
            bid_window_end: string | null;
            /**
             * Window Passed
             * @default false
             */
            window_passed: boolean;
            /** Bid Published At */
            bid_published_at: string | null;
            /**
             * Tender Out
             * @default false
             */
            tender_out: boolean;
            /** Conversion Prob */
            conversion_prob: number;
            /** Signal Count */
            signal_count: number;
            /**
             * First Seen At
             * Format: date
             */
            first_seen_at: string;
            /**
             * Last Signal At
             * Format: date
             */
            last_signal_at: string;
            /** Score */
            score: number | null;
            /** Reasons */
            reasons: string[];
            /** Feedback */
            feedback: string | null;
            /** Lead Days */
            lead_days: number | null;
            /** Head Start Days */
            head_start_days?: number | null;
        };
        /** OpportunityDetail */
        OpportunityDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            institution: components["schemas"]["InstitutionRef"];
            /** Department */
            department: string | null;
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Stage */
            stage: string;
            /** Stage Label */
            stage_label: string;
            /** Status */
            status: string;
            /** Est Budget Krw */
            est_budget_krw: number | null;
            /** Bid Window Start */
            bid_window_start: string | null;
            /** Bid Window End */
            bid_window_end: string | null;
            /**
             * Window Passed
             * @default false
             */
            window_passed: boolean;
            /** Bid Published At */
            bid_published_at: string | null;
            /**
             * Tender Out
             * @default false
             */
            tender_out: boolean;
            /** Conversion Prob */
            conversion_prob: number;
            /** Signal Count */
            signal_count: number;
            /**
             * First Seen At
             * Format: date
             */
            first_seen_at: string;
            /**
             * Last Signal At
             * Format: date
             */
            last_signal_at: string;
            /** Score */
            score: number | null;
            /** Reasons */
            reasons: string[];
            /** Feedback */
            feedback: string | null;
            /** Lead Days */
            lead_days: number | null;
            /** Head Start Days */
            head_start_days?: number | null;
            /** Keywords */
            keywords: string[];
            /** Best Commitment */
            best_commitment: string | null;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
            /** Budget Trajectory */
            budget_trajectory: components["schemas"]["BudgetPoint"][];
            /** Breakdown */
            breakdown: {
                [key: string]: unknown;
            } | null;
            /** Briefs */
            briefs: components["schemas"]["BriefOut"][];
        };
        /** OrgOut */
        OrgOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Plan */
            plan: string;
            /** Credit Balance */
            credit_balance: number;
        };
        /** OverviewOut */
        OverviewOut: {
            funnel: components["schemas"]["FunnelOut"];
            /** Jobs Last 24H */
            jobs_last_24h: {
                [key: string]: number;
            };
            /** Failed Jobs */
            failed_jobs: number;
            /** Llm Spent Today Usd */
            llm_spent_today_usd: number;
            /** Llm Daily Budget Usd */
            llm_daily_budget_usd: number;
            /** Queue Depth */
            queue_depth: number | null;
            /** Sources Unhealthy */
            sources_unhealthy: number;
        };
        /** PaymentOut */
        PaymentOut: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: string;
            /** Kind */
            kind: string;
            /** Order Name */
            order_name: string;
            /** Amount */
            amount: number;
            /** Status */
            status: string;
            /** Failure Message */
            failure_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Paid At */
            paid_at: string | null;
        };
        /** PlanChangeIn */
        PlanChangeIn: {
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "team";
        };
        /** PlanOut */
        PlanOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Monthly Price Krw */
            monthly_price_krw: number;
            /** Monthly Credits */
            monthly_credits: number;
            /** Max Regions */
            max_regions: number | null;
            /** Channels */
            channels: string[];
            /** Instant Alerts */
            instant_alerts: boolean;
        };
        /** ProfileIO */
        ProfileIO: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Keywords */
            keywords?: string[];
            /** Exclude Keywords */
            exclude_keywords?: string[];
            /** Categories */
            categories?: string[];
            /** Region Codes */
            region_codes?: string[];
            /** Budget Min */
            budget_min?: number | null;
            /** Budget Max */
            budget_max?: number | null;
        };
        /** RelationDecisionIn */
        RelationDecisionIn: {
            /** Project Id */
            project_id: number;
            /** Contract Id */
            contract_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "confirmed" | "rejected";
            /**
             * Expected Version
             * @description 0 for creation; otherwise the version shown to the reviewer
             */
            expected_version: number;
            /** Evidence Signal Ids */
            evidence_signal_ids?: number[];
            /** Note */
            note: string;
        };
        /** RelationEndpointOut */
        RelationEndpointOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Institution Code */
            institution_code: string | null;
            /** Stage */
            stage: string;
        };
        /** RelationEventOut */
        RelationEventOut: {
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "confirmed" | "rejected";
            /** Note */
            note: string;
            /** Actor User Id */
            actor_user_id: number | null;
            /** Actor Name */
            actor_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Signal Ids */
            evidence_signal_ids: number[];
            /** Evidence */
            evidence: components["schemas"]["RelationEvidenceOut"][];
        };
        /** RelationEvidenceOut */
        RelationEvidenceOut: {
            /** Signal Id */
            signal_id: number;
            /** Signal Title */
            signal_title: string;
            /** Stage */
            stage: string;
            /** Opportunity Id */
            opportunity_id: number;
            /** Document Id */
            document_id: number;
            /** Document Title */
            document_title: string;
            /** Document Url */
            document_url: string | null;
            /** Document Content Hash */
            document_content_hash: string;
            /** Source Text Sha256 */
            source_text_sha256: string;
            /** Fingerprint */
            fingerprint: string;
            /** Evidence */
            evidence: components["schemas"]["RelationQuoteOut"][];
        };
        /** RelationOut */
        RelationOut: {
            /** Id */
            id: number;
            /**
             * Kind
             * @constant
             */
            kind: "project_contract";
            /** Project Id */
            project_id: number;
            /** Contract Id */
            contract_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "confirmed" | "rejected";
            /**
             * Effective Status
             * @enum {string}
             */
            effective_status: "proposed" | "confirmed" | "rejected" | "stale";
            /** Valid */
            valid: boolean;
            /** Validity Reasons */
            validity_reasons: string[];
            /** Version */
            version: number;
            /** Evidence Signal Ids */
            evidence_signal_ids: number[];
            /** Evidence */
            evidence: components["schemas"]["RelationEvidenceOut"][];
            /** Note */
            note: string;
            /** Updated By */
            updated_by: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            project: components["schemas"]["RelationEndpointOut"] | null;
            contract: components["schemas"]["RelationEndpointOut"] | null;
            /** History */
            history: components["schemas"]["RelationEventOut"][];
        };
        /** RelationPageOut */
        RelationPageOut: {
            /** Items */
            items: components["schemas"]["RelationOut"][];
            /** Next After Id */
            next_after_id: number | null;
        };
        /** RelationQuoteOut */
        RelationQuoteOut: {
            /** Quote */
            quote: string;
            /** Source Quote */
            source_quote: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** ReviewDecisionIn */
        ReviewDecisionIn: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject" | "edit";
            /** Title */
            title?: string | null;
            /** Budget Krw */
            budget_krw?: number | null;
            /** Expected Year */
            expected_year?: number | null;
            /** Commitment */
            commitment?: ("committed" | "planned" | "reviewing" | "declined") | null;
            /** Institution Code */
            institution_code?: string | null;
            category?: components["schemas"]["Category"] | null;
        };
        /** ReviewItemOut */
        ReviewItemOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Reasons */
            reasons: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            signal: components["schemas"]["SignalOut"];
            /** Institution Name */
            institution_name: string | null;
        };
        /** SignalOut */
        SignalOut: {
            /** Id */
            id: number;
            /** Stage */
            stage: string;
            /** Stage Label */
            stage_label: string;
            /**
             * Observed At
             * Format: date
             */
            observed_at: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Category */
            category: string;
            /** Department */
            department: string | null;
            /** Budget Krw */
            budget_krw: number | null;
            /** Expected Year */
            expected_year: number | null;
            /** Expected Half */
            expected_half: string | null;
            /** Commitment */
            commitment: string | null;
            /** Confidence */
            confidence: number;
            /** Verdict */
            verdict: string;
            /** Extractor */
            extractor: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Context */
            context: string | null;
            /** Context Offset */
            context_offset: number | null;
            document: components["schemas"]["DocumentRef"];
            link: components["schemas"]["LinkOut"] | null;
        };
        /** SignupIn */
        SignupIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /** Company Name */
            company_name: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Adapter */
            adapter: string;
            /** Enabled */
            enabled: boolean;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Circuit */
            circuit: {
                [key: string]: unknown;
            };
            /** Documents */
            documents: number;
            /** Last Run */
            last_run: {
                [key: string]: unknown;
            } | null;
        };
        /** SourcePatchIn */
        SourcePatchIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** SourceRunIn */
        SourceRunIn: {
            /** Since */
            since?: string | null;
            /** Until */
            until?: string | null;
        };
        /** SubscriptionOut */
        SubscriptionOut: {
            /** Plan */
            plan: string;
            /** Status */
            status: string;
            /** Card Summary */
            card_summary: string | null;
            /** Current Period Start */
            current_period_start: string | null;
            /** Current Period End */
            current_period_end: string | null;
            /** Next Charge At */
            next_charge_at: string | null;
            /** Canceled At */
            canceled_at: string | null;
            /** Failed Attempts */
            failed_attempts: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Is Staff */
            is_staff: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileIO"];
                };
            };
        };
    };
    put_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileIO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    institutions_api_institutions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionOut"][];
                };
            };
        };
    };
    categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    feed_api_opportunities_get: {
        parameters: {
            query?: {
                stage?: string[] | null;
                category?: string[] | null;
                status?: string[] | null;
                q?: string | null;
                include_dismissed?: boolean;
                sort?: "score" | "soon" | "recent";
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_opportunities__opportunity_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_brief_api_opportunities__opportunity_id__briefs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_alerts_rule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleIO"];
                };
            };
        };
    };
    put_rule_api_alerts_rule_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleIO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleIO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    channels_api_alerts_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertChannelOut"][];
                };
            };
        };
    };
    add_channel_api_alerts_channels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertChannelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_alerts_channels__channel_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_channel_api_alerts_channels__channel_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notifications_api_alerts_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
        };
    };
    billing_api_billing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingOut"];
                };
            };
        };
    };
    card_api_billing_card_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_billing_plan_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    credits_api_billing_credits_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditPurchaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    sources_api_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    run_source_api_admin_sources__key__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_api_admin_sources__key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_admin_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                job?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_admin_jobs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_api_admin_review_get: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_review_api_admin_review__item_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_usage_api_admin_llm_usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMUsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evals_api_admin_evals_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_api_admin_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_relations_api_admin_relations_get: {
        parameters: {
            query?: {
                status?: ("proposed" | "confirmed" | "rejected") | null;
                after_id?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_relation_api_admin_relations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mixed_relations_api_admin_relations_mixed_get: {
        parameters: {
            query?: {
                after_id?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixedRelationPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_relation_api_admin_relations__relation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opportunity_relations_api_opportunities__opportunity_id__relations_get: {
        parameters: {
            query?: {
                after_id?: number;
                limit?: number;
            };
            header?: never;
            path: {
                opportunity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    toss_webhook_api_webhooks_toss_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
