"""Postgres job queue, API keys, usage metering, and tenant isolation with row-level security.

The queue's semantics live in SQL functions (``jobq_*``) so the Python stage workers and the
TypeScript orchestrator share one definition of claim, lease, heartbeat, retry and reaping
instead of two that drift.

Revision ID: 0005
Revises: 0004
"""

from alembic import op

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None

TABLES = """
ALTER TABLE organizations ADD COLUMN usage_cap_usd numeric(12, 4);

CREATE TABLE api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id bigint NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    prefix varchar(24) NOT NULL UNIQUE,
    secret_sha256 char(64) NOT NULL,
    scopes text[] NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    revoked_at timestamptz,
    CONSTRAINT ck_api_key_scopes CHECK (
        cardinality(scopes) > 0
        AND scopes <@ ARRAY['jobs:read', 'jobs:write', 'usage:read']::text[]
    )
);
CREATE INDEX ix_api_keys_org ON api_keys (org_id);

CREATE TABLE jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id bigint NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    kind varchar(64) NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'queued',
    priority smallint NOT NULL DEFAULT 0,
    payload jsonb NOT NULL DEFAULT '{}',
    dedupe_key varchar(200),
    parent_id bigint REFERENCES jobs (id) ON DELETE CASCADE,
    attempts integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    run_after timestamptz NOT NULL DEFAULT now(),
    locked_by varchar(128),
    lease_until timestamptz,
    heartbeat_at timestamptz,
    cancel_requested boolean NOT NULL DEFAULT false,
    progress jsonb NOT NULL DEFAULT '{}',
    result jsonb,
    error text,
    cost jsonb NOT NULL DEFAULT '{}',
    budget_usd numeric(12, 4),
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    finished_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_jobs_status
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT ck_jobs_attempts CHECK (attempts >= 0 AND max_attempts >= 1),
    -- A running job always has an owner and a lease; nothing else has either.
    CONSTRAINT ck_jobs_lease
        CHECK ((status = 'running') = (locked_by IS NOT NULL AND lease_until IS NOT NULL))
);
-- One queued, running or finished job per (tenant, kind, key): submitting the same video
-- again returns the job that has it. A failed or cancelled job frees the key.
CREATE UNIQUE INDEX uq_jobs_dedupe ON jobs (org_id, kind, dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status IN ('queued', 'running', 'succeeded');
CREATE INDEX ix_jobs_ready ON jobs (kind, priority DESC, run_after, id) WHERE status = 'queued';
CREATE INDEX ix_jobs_lease ON jobs (lease_until) WHERE status = 'running';
CREATE INDEX ix_jobs_org_created ON jobs (org_id, created_at DESC);
CREATE INDEX ix_jobs_parent ON jobs (parent_id) WHERE parent_id IS NOT NULL;

-- Keyed by what the work is about (a video's content hash), not by the job: a new job for
-- the same video picks up where a failed one stopped.
CREATE TABLE job_checkpoints (
    org_id bigint NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    scope varchar(200) NOT NULL,
    key varchar(300) NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (org_id, scope, key)
);

-- Append-only. One row per job and meter (the idempotency key), written in the transaction
-- that completes the job, so a job finished twice by two workers is billed once.
CREATE TABLE usage_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id bigint NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    job_id bigint REFERENCES jobs (id) ON DELETE SET NULL,
    meter varchar(32) NOT NULL,
    quantity numeric(18, 6) NOT NULL,
    usd numeric(12, 6) NOT NULL DEFAULT 0,
    idempotency_key varchar(200) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_usage_meter
        CHECK (meter IN ('stt_audio_seconds', 'ocr_frames', 'llm_tokens', 'compute_seconds')),
    CONSTRAINT ck_usage_non_negative CHECK (quantity >= 0 AND usd >= 0)
);
CREATE INDEX ix_usage_org_created ON usage_events (org_id, created_at);
"""

FUNCTIONS = r"""
-- Exponential backoff with equal jitter: half fixed, half random, so the jobs a provider
-- outage failed together do not all come back in the same second.
CREATE FUNCTION jobq_backoff(p_attempts integer, p_base_seconds integer, p_cap_seconds integer)
RETURNS interval LANGUAGE sql VOLATILE AS $$
    SELECT make_interval(secs => d / 2 + random() * d / 2)
    FROM (
        SELECT least(p_cap_seconds, p_base_seconds * power(2, greatest(p_attempts - 1, 0)))::float8
    ) AS s (d)
$$;

CREATE FUNCTION jobq_enqueue(
    p_org bigint,
    p_kind text,
    p_payload jsonb,
    p_dedupe_key text DEFAULT NULL,
    p_priority smallint DEFAULT 0,
    p_max_attempts integer DEFAULT 5,
    p_budget_usd numeric DEFAULT NULL,
    p_parent_id bigint DEFAULT NULL,
    p_run_after timestamptz DEFAULT now()
) RETURNS TABLE (job_id bigint, created boolean) LANGUAGE plpgsql AS $$
#variable_conflict use_column
DECLARE
    v_id bigint;
BEGIN
    -- Two tries: the job holding the key can fail between the conflict and the lookup,
    -- which frees the key for this insert.
    FOR i IN 1..2 LOOP
        INSERT INTO jobs (org_id, kind, payload, dedupe_key, priority, max_attempts,
                          budget_usd, parent_id, run_after)
        VALUES (p_org, p_kind, p_payload, p_dedupe_key, p_priority, p_max_attempts,
                p_budget_usd, p_parent_id, p_run_after)
        ON CONFLICT (org_id, kind, dedupe_key)
            WHERE dedupe_key IS NOT NULL AND status IN ('queued', 'running', 'succeeded')
            DO NOTHING
        RETURNING id INTO v_id;
        IF v_id IS NOT NULL THEN
            PERFORM pg_notify('jobq', p_kind);
            RETURN QUERY SELECT v_id, true;
            RETURN;
        END IF;
        SELECT id INTO v_id FROM jobs
        WHERE org_id = p_org AND kind = p_kind AND dedupe_key = p_dedupe_key
          AND status IN ('queued', 'running', 'succeeded');
        IF v_id IS NOT NULL THEN
            RETURN QUERY SELECT v_id, false;
            RETURN;
        END IF;
    END LOOP;
    RAISE EXCEPTION 'jobq_enqueue: could not insert or find % %', p_kind, p_dedupe_key;
END
$$;

-- The oldest ready job of the given kinds, highest priority first. SKIP LOCKED lets any
-- number of workers claim at once without waiting on each other's row locks.
CREATE FUNCTION jobq_claim(p_worker text, p_kinds text[], p_lease_seconds integer)
RETURNS SETOF jobs LANGUAGE sql AS $$
    UPDATE jobs AS j
    SET status = 'running',
        attempts = j.attempts + 1,
        locked_by = p_worker,
        lease_until = now() + make_interval(secs => p_lease_seconds),
        heartbeat_at = now(),
        started_at = coalesce(j.started_at, now()),
        updated_at = now()
    WHERE j.id = (
        SELECT id FROM jobs
        WHERE status = 'queued' AND kind = ANY (p_kinds) AND run_after <= now()
        ORDER BY priority DESC, run_after, id
        FOR UPDATE SKIP LOCKED
        LIMIT 1
    )
    RETURNING j.*
$$;

-- 'ok', 'cancel' (someone asked to stop: finish with jobq_fail) or 'lost' (the lease expired
-- and the job was reaped or taken; stop without writing anything).
CREATE FUNCTION jobq_heartbeat(
    p_job bigint, p_worker text, p_lease_seconds integer, p_progress jsonb DEFAULT NULL
) RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    v_cancel boolean;
BEGIN
    UPDATE jobs
    SET lease_until = now() + make_interval(secs => p_lease_seconds),
        heartbeat_at = now(),
        progress = coalesce(p_progress, progress),
        updated_at = now()
    WHERE id = p_job AND status = 'running' AND locked_by = p_worker
    RETURNING cancel_requested INTO v_cancel;
    IF NOT FOUND THEN
        RETURN 'lost';
    END IF;
    RETURN CASE WHEN v_cancel THEN 'cancel' ELSE 'ok' END;
END
$$;

CREATE FUNCTION jobq_complete(
    p_job bigint, p_worker text, p_result jsonb, p_cost jsonb DEFAULT '{}'
) RETURNS boolean LANGUAGE sql AS $$
    WITH done AS (
        UPDATE jobs
        SET status = 'succeeded', result = p_result, cost = p_cost, error = NULL,
            locked_by = NULL, lease_until = NULL, finished_at = now(), updated_at = now()
        WHERE id = p_job AND status = 'running' AND locked_by = p_worker
        RETURNING id
    )
    SELECT EXISTS (SELECT 1 FROM done)
$$;

-- 'retry' (queued again after a backoff), 'failed', 'cancelled', or 'lost'.
CREATE FUNCTION jobq_fail(
    p_job bigint,
    p_worker text,
    p_error text,
    p_retryable boolean,
    p_base_seconds integer DEFAULT 15,
    p_cap_seconds integer DEFAULT 3600,
    p_cost jsonb DEFAULT NULL
) RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    j jobs;
    v_outcome text;
BEGIN
    SELECT * INTO j FROM jobs
    WHERE id = p_job AND status = 'running' AND locked_by = p_worker
    FOR UPDATE;
    IF NOT FOUND THEN
        RETURN 'lost';
    END IF;
    v_outcome := CASE
        WHEN j.cancel_requested THEN 'cancelled'
        WHEN p_retryable AND j.attempts < j.max_attempts THEN 'retry'
        ELSE 'failed'
    END;
    UPDATE jobs
    SET status = CASE v_outcome WHEN 'retry' THEN 'queued' ELSE v_outcome END,
        run_after = CASE v_outcome
            WHEN 'retry' THEN now() + jobq_backoff(j.attempts, p_base_seconds, p_cap_seconds)
            ELSE run_after
        END,
        finished_at = CASE v_outcome WHEN 'retry' THEN NULL ELSE now() END,
        error = p_error,
        cost = coalesce(p_cost, cost),
        locked_by = NULL,
        lease_until = NULL,
        updated_at = now()
    WHERE id = p_job;
    RETURN v_outcome;
END
$$;

-- Jobs whose worker stopped heartbeating (killed, OOM, network partition) go back to the
-- queue with a backoff, or fail once they have used their attempts.
CREATE FUNCTION jobq_reap(p_base_seconds integer DEFAULT 15, p_cap_seconds integer DEFAULT 3600)
RETURNS integer LANGUAGE plpgsql AS $$
DECLARE
    n integer;
BEGIN
    WITH expired AS (
        SELECT id FROM jobs
        WHERE status = 'running' AND lease_until < now()
        FOR UPDATE SKIP LOCKED
    )
    UPDATE jobs AS j
    SET status = CASE
            WHEN j.cancel_requested THEN 'cancelled'
            WHEN j.attempts < j.max_attempts THEN 'queued'
            ELSE 'failed'
        END,
        run_after = CASE
            WHEN NOT j.cancel_requested AND j.attempts < j.max_attempts
            THEN now() + jobq_backoff(j.attempts, p_base_seconds, p_cap_seconds)
            ELSE j.run_after
        END,
        finished_at = CASE
            WHEN j.cancel_requested OR j.attempts >= j.max_attempts THEN now()
        END,
        error = 'lease expired: ' || j.locked_by || ' stopped heartbeating',
        locked_by = NULL,
        lease_until = NULL,
        updated_at = now()
    FROM expired
    WHERE j.id = expired.id;
    GET DIAGNOSTICS n = ROW_COUNT;
    RETURN n;
END
$$;

-- Cancels the job and everything under it: queued jobs at once, running ones at their next
-- heartbeat. Under row-level security another tenant's job is simply 'not_found'.
CREATE FUNCTION jobq_cancel(p_job bigint) RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    v_status text;
BEGIN
    WITH RECURSIVE tree AS (
        SELECT id FROM jobs WHERE id = p_job
        UNION ALL
        SELECT c.id FROM jobs AS c JOIN tree AS t ON c.parent_id = t.id
    ),
    queued AS (
        UPDATE jobs SET status = 'cancelled', finished_at = now(), updated_at = now()
        WHERE id IN (SELECT id FROM tree) AND status = 'queued'
        RETURNING id
    )
    UPDATE jobs SET cancel_requested = true, updated_at = now()
    WHERE id IN (SELECT id FROM tree) AND status = 'running';
    SELECT status INTO v_status FROM jobs WHERE id = p_job;
    RETURN CASE
        WHEN v_status IS NULL THEN 'not_found'
        WHEN v_status = 'running' THEN 'cancelling'
        ELSE v_status
    END;
END
$$;
"""

# The API answers each request as ``app_tenant`` with ``app.org_id`` set for that transaction
# (``SET LOCAL ROLE app_tenant``). The role is not the tables' owner, so the policies apply to
# it even when the login role is a superuser; the workers keep the owner's view of every tenant.
TENANCY = """
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_tenant') THEN
        CREATE ROLE app_tenant NOLOGIN;
    END IF;
END
$$;
GRANT app_tenant TO CURRENT_USER;
GRANT USAGE ON SCHEMA public TO app_tenant;
GRANT SELECT, INSERT ON jobs TO app_tenant;
GRANT UPDATE (status, cancel_requested, finished_at, updated_at) ON jobs TO app_tenant;
GRANT SELECT ON usage_events TO app_tenant;

REVOKE EXECUTE ON FUNCTION jobq_claim(text, text[], integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION jobq_heartbeat(bigint, text, integer, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION jobq_complete(bigint, text, jsonb, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION
    jobq_fail(bigint, text, text, boolean, integer, integer, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION jobq_reap(integer, integer) FROM PUBLIC;

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY jobs_tenant ON jobs TO app_tenant
    USING (org_id = current_setting('app.org_id')::bigint)
    WITH CHECK (org_id = current_setting('app.org_id')::bigint);
ALTER TABLE usage_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY usage_tenant ON usage_events TO app_tenant
    USING (org_id = current_setting('app.org_id')::bigint);
-- No policy and no grant: a tenant session sees neither keys nor checkpoints.
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_checkpoints ENABLE ROW LEVEL SECURITY;
"""


def _statements(sql: str) -> list[str]:
    """One statement per execute (asyncpg prepares each); ``$$`` bodies keep their ``;``."""
    out: list[str] = []
    buf: list[str] = []
    quoted = False
    for line in sql.splitlines():
        buf.append(line)
        quoted ^= line.count("$$") % 2 == 1
        if not quoted and line.rstrip().endswith(";"):
            out.append("\n".join(buf).strip())
            buf = []
    if "\n".join(buf).strip():
        out.append("\n".join(buf).strip())
    return out


def upgrade() -> None:
    for sql in (TABLES, FUNCTIONS, TENANCY):
        for statement in _statements(sql):
            op.execute(statement)


def downgrade() -> None:
    for statement in _statements(
        """
        DROP TABLE IF EXISTS usage_events, job_checkpoints, jobs, api_keys CASCADE;
        DROP FUNCTION IF EXISTS jobq_backoff, jobq_enqueue, jobq_claim, jobq_heartbeat,
            jobq_complete, jobq_fail, jobq_reap, jobq_cancel;
        ALTER TABLE organizations DROP COLUMN IF EXISTS usage_cap_usd;
        """
    ):
        op.execute(statement)
